# Generated by Django 5.1.2 on 2025-11-19 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('highest_degree', models.CharField(blank=True, max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('subjects', models.CharField(blank=True, max_length=300)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tutor_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='tutor_resumes/')),
                ('cover_letter', models.TextField()),
                ('availability', models.CharField(max_length=200)),
                ('rates', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutorprofile')),
            ],
        ),
    ]
