# Generated by Django 5.1.2 on 2025-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tutorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplication',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='authorized',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='convicted',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='conviction_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='desired_salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='notice_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='teaching_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='address_standard',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='address_uni',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='lat_standard',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='lat_uni',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='lng_standard',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='lng_uni',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='subject_standard_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='subject_uni_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='university_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
